spring.application.name=demo
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=du_an;encrypt=false
spring.datasource.username=sa
spring.datasource.password=your_password

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect